### ISSUE TITLE
Restructure the current project

### ISSUE THREAD

**Issue by maticoblak** [maticoblak/workshop#1]
Create OOP procedure to use to use the openGL tools.
- [ ] Crate Context object class described at #2 
- [ ] Create Frame buffer object class described at #4 
- [ ] Create Shader object class described at #3
